--- Tabla temporal 
CREATE TABLE TempData (
    FECHA_PROCESO DATETIME,
    RUC_PROVEEDOR VARCHAR(20),
    PROVEEDOR VARCHAR(255),
    RUC_ENTIDAD VARCHAR(20),
    ENTIDAD VARCHAR(255),
    TIPO_PROCEDIMIENTO VARCHAR(50),
    ORDEN_ELECTRÓNICA VARCHAR(50),
    ORDEN_ELECTRÓNICA_GENERADA VARCHAR(255),
    ESTADO_ORDEN_ELECTRÓNICA VARCHAR(50),
    DOCUMENTO_ESTADO_OCAM VARCHAR(200),
    FECHA_FORMALIZACIÓN DATETIME,
    FECHA_ÚLTIMO_ESTADO DATETIME,
    SUB_TOTAL DECIMAL(18, 2),
    IGV DECIMAL(18, 2),
    TOTAL DECIMAL(18, 2),
    ORDEN_DIGITALIZADA VARCHAR(255),
    DESCRIPCIÓN_ESTADO VARCHAR(255),
    DESCRIPCIÓN_CESIÓN_DERECHOS VARCHAR(255),
    ACUERDO_MARCO VARCHAR(255)
);

select * from TempData